# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SpamMonkey
version:      0.02
version_from: lib/SpamMonkey.pm
installdirs:  site
requires:
    File::Path::Expand:            0
    UNIVERSAL::require:            0
    URI::Find:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
